# Generated by Django 3.0.1 on 2020-02-27 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_auto_20200227_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(choices=[('SE', 'Software Engineer'), ('AE', 'Automobile Engineer'), ('DS', 'Data Scientist'), ('BD', 'Backend Developer'), ('FD', 'Frontend Developer'), ('FSD', 'Full Stack Developer'), ('SE', 'System Engineer'), ('DE', 'DevOps Enginner')], max_length=40)),
                ('job_description', models.FileField(upload_to='resume')),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
