# Generated by Django 3.0.1 on 2020-02-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_review_job_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='job_text',
            field=models.TextField(blank=True),
        ),
    ]
